#!/bin/sh

#
# Run the hook command.
# $(GENERATED_MESSAGE)
#

GIT_USER_NAME=$(git config user.name)
GIT_USER_EMAIL=$(git config user.email)
COMMIT_MESSAGE_FILE=$1

# Fetch the GIT diff and format it as command input:
DIFF=$(git diff -r -p -m -M --full-index --staged | cat)

# Run
(cd "${HOOK_EXEC_PATH}" && printf "%s\n" "${DIFF}" | exec $(HOOK_COMMAND) '--ansi' "--git-user-name=$GIT_USER_NAME" "--git-user-email=$GIT_USER_EMAIL" "$COMMIT_MESSAGE_FILE")
