services:
  console.input:
    class: Symfony\Component\Console\Input\ArgvInput
    synthetic: true

  console.output:
    class: Symfony\Component\Console\Output\ConsoleOutput
    synthetic: true

  console.config-file:
    class: ClickNow\Checker\Console\ConfigFile
    synthetic: true

  console.command.run:
    class: ClickNow\Checker\Console\Command\RunCommand
    arguments:
      - '@runner.commands-collection'
      - '@repository.git'

  console.command.self-update:
    class: ClickNow\Checker\Console\Command\SelfUpdateCommand
    arguments:
      - '@io'
      - '@phar.updater'

  console.command.git.install:
    class: ClickNow\Checker\Console\Command\Git\InstallCommand
    arguments:
      - '@checker'
      - '@repository.filesystem'
      - '@io'
      - '@process-builder'
      - '%git-hooks%'

  console.command.git.commit-msg:
    class: ClickNow\Checker\Console\Command\Git\CommitMsgCommand
    arguments:
      - '@runner.git-hook.commit-msg'
      - '@repository.git'
      - '@repository.filesystem'

  console.command.git.pre-commit:
    class: ClickNow\Checker\Console\Command\Git\PreCommitCommand
    arguments:
      - '@runner.git-hook.pre-commit'
      - '@repository.git'

  console.command.git.pre-push:
    class: ClickNow\Checker\Console\Command\Git\PrePushCommand
    arguments:
      - '@runner.git-hook.pre-push'
      - '@repository.git'

  console.command.git.uninstall:
    class: ClickNow\Checker\Console\Command\Git\UninstallCommand
    arguments:
      - '@repository.filesystem'
      - '@io'
      - '%git-hooks%'
