services:
  logger:
    class: Monolog\Logger
    arguments:
      - 'Checker'
      - ['@logger.handler.null-handler']

  logger.handler.null-handler:
    class: Monolog\Handler\NullHandler
    public: false
