services:
  repository.filesystem:
    class: ClickNow\Checker\Repository\Filesystem

  repository.git:
    class: ClickNow\Checker\Repository\Git
    arguments:
      - '@git.repository'
      - '@repository.filesystem'
      - '@process-builder'
