services:
  subscriber.progress:
    class: ClickNow\Checker\Subscriber\ProgressSubscriber
    arguments:
      - '@io'
    tags:
      - { name: checker.event-subscriber }

  subscriber.report:
    class: ClickNow\Checker\Subscriber\ReportSubscriber
    arguments:
      - '@io'
      - '@helper.paths'
    tags:
      - { name: checker.event-subscriber }

  subscriber.stash-unstaged-changes:
    class: ClickNow\Checker\Subscriber\StashUnstagedChangesSubscriber
    arguments:
      - '@io'
      - '@repository.git'
    tags:
      - { name: checker.event-subscriber }
