services:
  subscriber.progress-list:
    class: ClickNow\Checker\Subscriber\ProgressListSubscriber
    arguments:
      - '@io'
    tags:
      - { name: checker.event-subscriber }

  subscriber.progress-bar:
    class: ClickNow\Checker\Subscriber\ProgressBarSubscriber
    arguments:
      - '@io'
    tags:
      - { name: checker.event-subscriber }

  subscriber.report:
    class: ClickNow\Checker\Subscriber\ReportSubscriber
    arguments:
      - '@io'
      - '@helper.paths'
    tags:
      - { name: checker.event-subscriber }

  subscriber.stash-unstaged-changes:
    class: ClickNow\Checker\Subscriber\StashUnstagedChangesSubscriber
    arguments:
      - '@io'
      - '@git.repository'
    tags:
      - { name: checker.event-subscriber }
