PHP: true

engines:
  duplication:
    enabled: false

  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR2"

  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml.dist"

ratings:
  paths:
    - "**.php"
