PHP: true

ratings:
  paths:
    - src/**/*.php
    - tests/**/*.php

engines:
  duplication:
    enabled: false

  phpcodesniffer:
    enabled: true
    config:
      standard: psr2

  phpmd:
    enabled: true
    config:
      rulesets: phpmd.xml.dist
