PHP: true

exclude_paths:
  - "tests/**/*"

engines:
  duplication:
  	enabled: false

  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR2"

  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "ruleset.xml"

ratings:
  paths:
    - "**.php"
