preset: none

risky: true

enabled:
  - align_double_arrow
  - alpha_ordered_imports
  - binary_operator_spaces
  - blank_line_after_namespace
  - blank_line_after_opening_tag
  - blank_line_before_return
  - braces
  - cast_spaces
  - class_definition
  - combine_consecutive_unsets
  - concat_without_spaces
  - declare_equal_normalize
  - dir_constant
  - elseif
  - encoding
  - ereg_to_preg
  - full_opening_tag
  - function_declaration
  - function_typehint_space
  - hash_to_slash_comment
  - heredoc_to_nowdoc
  - include
  - linebreak_after_opening_tag
  - lowercase_cast
  - lowercase_constants
  - lowercase_keywords
  - method_argument_space
  - method_separation
  - method_visibility_required
  - modernize_types_casting
  - native_function_casing
  - new_with_braces
  - no_alias_functions
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_between_imports
  - no_blank_lines_between_traits
  - no_closing_tag
  - no_extra_block_blank_lines
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_php4_constructor
  - no_short_bool_cast
  - no_short_echo_tag
  - no_singleline_whitespace_before_semicolons
  - no_spaces_after_function_name
  - no_spaces_inside_offset
  - no_spaces_inside_parenthesis
  - no_spaces_outside_offset
  - no_tab_indentation
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_trailing_whitespace
  - no_trailing_whitespace_in_comment
  - no_unneeded_control_parentheses
  - no_unreachable_default_argument_value
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - normalize_index_brace
  - object_operator_without_whitespace
  - php_unit_fqcn_annotation
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_link_to_see
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_single_line_var_spacing
  - phpdoc_summary
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - pre_increment
  - print_to_echo
  - property_visibility_required
  - psr4
  - return_type_declaration
  - self_accessor
  - short_array_syntax
  - short_scalar_cast
  - single_blank_line_at_eof
  - single_blank_line_before_namespace
  - single_class_element_per_statement
  - single_import_per_statement
  - single_line_after_imports
  - single_line_class_definition
  - single_quote
  - space_after_semicolon
  - standardize_not_equals
  - switch_case_semicolon_to_colon
  - switch_case_space
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unalign_equals
  - unary_operator_spaces
  - unix_line_endings

finder:
  name:
    - "*.php"

  path:
    - "src"
    - "tests"
