services:
  console.input:
    class: Symfony\Component\Console\Input\ArgvInput
    synthetic: true

  console.output:
    class: Symfony\Component\Console\Output\ConsoleOutput
    synthetic: true

  console.config_file:
    class: ClickNow\Checker\Console\ConfigFile
    synthetic: true
