services:
  io:
    alias: io.console

  io.null:
    class: ClickNow\Checker\IO\NullIO
    public: false

  io.console:
    class: ClickNow\Checker\IO\ConsoleIO
    lazy: true
    arguments:
      - '@console.input'
      - '@console.output'
