parameters:
  bin_dir: ./vendor/bin
  git_dir: .
  hooks_dir: ~
  hooks_preset: local
  process_timeout: 60
  process_async_wait: 1000
  process_async_limit: 10
  stop_on_failure: false
  ignore_unstaged_changes: false
  skip_success_output: false
  message:
    successfully: successfully.txt
    failed: failed.txt
  extensions: []
  tasks: ~
  hooks: ~
  commands: ~
