services:
  subscriber.progress:
    class: ClickNow\Checker\Subscriber\ProgressSubscriber
    arguments:
      - '@io'
    tags:
      - { name: checker.event_subscriber }

  subscriber.report:
    class: ClickNow\Checker\Subscriber\ReportSubscriber
    arguments:
      - '@io'
      - '@helper.paths'
    tags:
      - { name: checker.event_subscriber }

  subscriber.stash_unstaged_changes:
    class: ClickNow\Checker\Subscriber\StashUnstagedChangesSubscriber
    arguments:
      - '@io'
      - '@git.repository'
    tags:
      - { name: checker.event_subscriber }
